# Generated by Django 3.0.3 on 2020-08-24 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200824_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 24, 14, 22, 14, 742160, tzinfo=utc)),
        ),
    ]
